export const UPDATE_FILTER_ARR = 'UPDATE_FILTER_ARR';
export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const UPDATE_FINAL_LIST = 'UPDATE_FINAL_LIST';
export const UPDATE_SHOW_MODAL = 'UPDATE_SHOW_MODAL';
export const UPDATE_URL = 'UPDATE_URL';
export const CONCAT_MASTER = 'CONCAT_MASTER';
